services:
  - type: web
    name: b-manager-api
    env: docker
    plan: free
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
